#提供一个有副本的状态集

# 使用 rbd 创建 kube 池
# 检查每个节点可否挂载
# rbd create test -p rbd
# rbd map kube/test 
# rbd unmap kube/test
# rbd rm kube/test

apiVersion: v1
kind: Secret
metadata:
  name: ceph-admin-secret
type: "kubernetes.io/rbd"
data:
  # ceph auth get-key client.admin | base64
  key: QVFCTTJRdGJobVRoRUJBQW55UmZFeWROZ2NvWDVULzFwbE5yaEE9PQ==
---
apiVersion: v1
kind: Secret
metadata:
  name: ceph-user-secret
type: "kubernetes.io/rbd"
data:
  # ceph auth add client.kube mon 'allow r' osd 'allow rwx pool=kube'
  # ceph auth get-key client.kube | base64
  key: QVFDNDNRdGJEcHlvSFJBQUVxTVhBelkra3lkRGZVNEhiaG96R3c9PQ==


#default 空间的默认存储类 provisioner  ceph.com/rbd
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: default
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: ceph.com/rbd
parameters:
    monitors: 192.168.4.250:6789,192.168.4.251:6789
    adminId: admin
    adminSecretName: ceph-admin-secret
    adminSecretNamespace: default
    pool: kube
    userId: kube
    userSecretName: ceph-user-secret
    imageFormat: "2"
    imageFeatures: layering