# statefulset service
apiVersion: v1
kind: Service
metadata:
    name: mongodb-mr
    labels:
      name: mongodb-mr
spec:
    ports:
    - port: 27017
      targetPort: 27017
    selector:
      name: mongodb-mr

#启动一个rbd - statefulSet nginx
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: mongodb-mr
spec:
  serviceName: mongodb-mr
  replicas: 1
  template:
    metadata:
      labels:
        name: mongodb-mr
    spec:
      containers:
        - name: mongo
          image: mongo:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: datapath
              mountPath: "/data"

  volumeClaimTemplates:
  - metadata:
      name: datapath
      annotations:
        volume.alpha.kubernetes.io/storage-class: default
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 50Gi