# statefulset service
apiVersion: v1
kind: Service
metadata:
    name: mysql-ss
    labels:
      name: mysql-ss
spec:
    ports:
    - port: 3306
      targetPort: 3306
    selector:
      name: mysql-ss

#启动一个rbd - statefulSet mysql
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: mysql-ss
spec:
  serviceName: mysql-ss
  replicas: 1
  template:
    metadata:
      labels:
        name: mysql-ss
    spec:
      containers:
        - name: mysql
          image: mysql:5.7
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: database
              mountPath: "/var/lib/mysql"
          env:
          - name: MYSQL_ROOT_PASSWORD
            value: "123456"
          command: ["rm -rf /var/lib/mysql/lost+found"]
  volumeClaimTemplates:
  - metadata:
      name: database
      annotations:
        volume.alpha.kubernetes.io/storage-class: default
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 50Gi