# statefulset service
apiVersion: v1
kind: Service
metadata:
    name: nginx-ss
    labels:
      name: nginx-ss
spec:
    ports:
    - port: 80
      targetPort: 80
    selector:
      name: nginx-ss

#启动一个rbd - statefulSet nginx
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: nginx-ss
spec:
  serviceName: nginx-ss
  replicas: 1
  template:
    metadata:
      labels:
        name: nginx-ss
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          volumeMounts:
            - name: www
              mountPath: "/usr/share/nginx/html"

  volumeClaimTemplates:
  - metadata:
      name: www
      annotations:
        volume.alpha.kubernetes.io/storage-class: default
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi